--[[
LuCI - Lua Configuration Interface
Version definition - do not edit this file
]]--
local open = io.open

module "luci.version"

distname    = "Host System"
distversion = "SDK"
luciname    = "LuCI"
luciversion = "no-tlink"

local f = open("/etc/openwrt_release")
if f then
    for line in f:lines() do
        local k, v = line:match('^([%w_]+)="?([^"]*)"?$')
        if k == "DISTRIB_DESCRIPTION" then distversion = v end
        if k == "DISTRIB_REVISION" and v ~= "unknown" then luciversion = v end
    end
    f:close()
end